name: "benchmark"
description: "run performance benchmark (for macos only)"

runs:
  using: "composite"
  steps:
    - name: run mcfost set up (downloads additional files)
      shell: bash
      working-directory: src
      env:
        MCFOST_UTILS: ${{ github.workspace }}/utils
      run: |
        chmod +x mcfost
        ./mcfost -setup

    - name: download phantom input file
      shell: bash
      run: |
        wget http://ipag.osug.fr/public/pintec/mcfost/test_data/discF_00500
        mv discF_00500 test_suite/test_data/discF_00500/

    - name: run benchmark
      shell: bash
      working-directory: src
      env:
        MCFOST_UTILS: ${{ github.workspace }}/utils
      run: |
        brew install gnu-time
        gtime -o ../benchmark-${{ matrix.compiler }}.tim --format=%E ./mcfost ../test_suite/test_data/discF_00500/discF_00500.para -phantom ../test_suite/test_data/discF_00500/discF_00500 -mol
