name: "macos"
description: "macos dependencies"

runs:
  using: "composite"
  steps:
    # Check if the dependency cache exists
    # If it does, restore those paths; otherwise these paths are cached at the end of the workflow
    # NOTE: Cache can be cleared manually from the Github actions webpage
    - name: cache dependencies
      id: cache-deps
      uses: actions/cache@v3
      with:
        path: |
          /usr/local/Cellar/gcc/
          /usr/local/Cellar/cfitsio/
          /usr/local/Cellar/voro-dev/
          /usr/local/Cellar/sprng2/
        key: TESTmcfost-deps-${{ runner.os }}

      # Symlinks to the path need to be created again after the cache is restored
    - name: add brew links
      if: ${{ steps.cache-deps.outputs.cache-hit == 'true' }}
      shell: bash
      run: |
        brew unlink gcc
        brew link gcc
        brew link cfitsio
        brew link voro-dev
        brew link sprng2

      # Only do these install steps if no cache is found
    - name: install deps
      if: ${{ steps.cache-deps.outputs.cache-hit != 'true' }}
      shell: bash
      run: |
        brew tap danieljprice/all
        brew reinstall gcc
        brew install cfitsio voro-dev sprng2

    # Always install hdf5, it's too problematic to cache (because it has dependencies)
    - name: install hdf5
      shell: bash
      run: |
        export CC=icc
        export FC=ifort
        export CXX=icpc
        export CFLAGS=""
        wget -N https://support.hdfgroup.org/ftp/HDF5/current/src/hdf5-1.10.5.tar.bz2
        echo "Compiling HDF5 ..."
        tar xjvf hdf5-1.10.5.tar.bz2
        cd hdf5-1.10.5
        mkdir -p "$HOME/hdf5_install_tmp"
        ./configure --prefix="$HOME/hdf5_install_tmp" --enable-fortran --disable-shared
        make install
        \cp "$HOME/hdf5_install_tmp/lib/libhdf5.a" "$HOME/hdf5_install_tmp/lib/libhdf5_fortran.a" /usr/lib/
        mkdir /usr/include/hdf5
        \cp "$HOME"/hdf5_install_tmp/include/*.h /usr/include/hdf5/
        \cp "$HOME"/hdf5_install_tmp/include/*.mod /usr/include/
        echo "Done" 
      # brew install hdf5
