name: "macos"
description: "macos dependencies"

runs:
  using: "composite"
  steps:
    # Check if the dependency cache exists
    # If it does, restore those paths; otherwise these paths are cached at the end of the workflow
    # NOTE: Cache can be cleared manually from the Github actions webpage
    - name: cache dependencies
      id: cache-deps
      uses: actions/cache@v3
      with:
        path: |
          /usr/local/Cellar/gcc/
          /usr/local/Cellar/cfitsio/
          /usr/local/Cellar/voro-dev/
          /usr/local/Cellar/sprng2/
        key: mcfost-deps-${{ runner.os }}

      # Symlinks to the path need to be created again after the cache is restored
    - name: add brew links
      if: ${{ steps.cache-deps.outputs.cache-hit == 'true' }}
      shell: bash
      run: |
        brew unlink gcc
        brew link gcc
        brew link cfitsio
        brew link voro-dev
        brew link sprng2

      # Only do these install steps if no cache is found
    - name: install deps
      if: ${{ steps.cache-deps.outputs.cache-hit != 'true' }}
      shell: bash
      run: |
        brew tap danieljprice/all
        brew reinstall gcc
        brew install cfitsio voro-dev sprng2

    # Always install hdf5, it's too problematic to cache (because it has dependencies)
    - name: install hdf5
      shell: bash
      run:  brew install hdf5
