name: "release"
description: "release"

runs:
  using: "composite"
  steps:
    - name: prepare tarball
      working-directory: src
      shell: bash
      run: tar -cvzf mcfost.tar.gz mcfost

    - name: Add binary to release
      uses: shogo82148/actions-upload-release-asset@v1.6.6
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: src/mcfost.tar.gz
        asset_name: ${{ format('mcfost_{0}-{1}.tar.gz', runner.os, runner.arch) }}
