name: "linux"
description: "linux dependencies"
inputs:
  compiler:
    description: Which compiler to use (gnu or intel?)
    required: true

# Note: needs GCC > 12, and sudo, wherever you're building
# Using gcc-11 will return a bug when compiling gas/wavelengths_gas.f90

runs:
  using: "composite"
  steps:

    # hdf5.mod file is located at /usr/lib64/gfortran/modules/ on almalinux
    - name: install hdf5 for gnu build
      if: ${{ matrix.toolchain.compiler == 'gfortran' }}
      shell: bash
      run: |
        dnf install -y sudo wget epel-release
        dnf install -y hdf5-static redhat-lsb-core
        cd /usr/include && ln -s /usr/lib64/gfortran/modules/* .

    - name: install hdf5 for intel build
      if: ${{ matrix.toolchain.compiler == 'ifort' }}
      shell: bash
      run: |
        export CC=icc
        export FC=ifort
        export CXX=icpc
        export CFLAGS=""
        wget -N https://support.hdfgroup.org/ftp/HDF5/current/src/hdf5-1.10.5.tar.bz2
        tar xjvf hdf5-1.10.5.tar.bz2
        cd hdf5-1.10.5
        mkdir -p "$HOME/hdf5_install_tmp"
        ./configure --prefix="$HOME/hdf5_install_tmp" --enable-fortran --disable-shared
        make install
        \cp "$HOME/hdf5_install_tmp/lib/libhdf5.a" "$HOME/hdf5_install_tmp/lib/libhdf5_fortran.a" /usr/lib/
        mkdir /usr/include/hdf5
        \cp "$HOME"/hdf5_install_tmp/include/*.h /usr/include/hdf5/
        \cp "$HOME"/hdf5_install_tmp/include/*.mod /usr/include/
        apt install zlib1g -y

    # Cache other dependencies for mcfost to avoid downloading/installing them each time this workflow runs
    - name: cache dependencies
      id: cache-deps
      uses: actions/cache@v3
      with:
        path: ${{ env.MCFOST_INSTALL }}
        key: mcfost-deps-${{ runner.os }}-${{ inputs.compiler }}

    # Only do this (lengthy) setup if dependency cache not found
    - name: prepare mcfost environment
      if: ${{ steps.cache-deps.outputs.cache-hit != 'true' }}
      shell: bash
      working-directory: lib
      run: |
        export LD_LIBRARY_PATH=LD_LIBRARY_PATH:/lib/x86_64-linux-gnu/
        ./install.sh
