name: "linux"
description: "linux dependencies"

# Note: needs GCC > 12, and sudo, wherever you're building
# Using gcc-11 will return a bug when compiling gas/wavelengths_gas.f90

runs:
  using: "composite"
  steps:
    # Cache dependencies for mcfost to avoid downloading/installing them each time this workflow runs
    - name: cache dependencies
      id: cache-deps
      uses: actions/cache@v3
      with:
        path: ${{ env.MCFOST_INSTALL }}
        key: mcfost-deps-${{ runner.os }}-${{ hashFiles('lib/install.sh') }}

    # Only do this (lengthy) setup if dependency cache not found
    - name: prepare mcfost environment
      if: ${{ steps.cache-deps.outputs.cache-hit != 'true' }}
      shell: bash
      working-directory: lib
      run: ./install.sh
