name: "linux"
description: "linux dependencies"

# Note: needs GCC > 12, and sudo, wherever you're building
# Using gcc-11 will return a bug when compiling gas/wavelengths_gas.f90

runs:
  using: "composite"
  steps:

    # hdf5.mod file is located at /usr/lib64/gfortran/modules/ on almalinux
    - name: install hdf5 for gnu build
      if: ${{ matrix.compiler == 'gfortran' }}
      shell: bash
      run: |
        dnf install -y sudo wget epel-release
        dnf install -y hdf5-static redhat-lsb-core
        cd $HDF5_DIR/include && ln -s /usr/lib64/gfortran/modules/* .

    # hdf5 needs to be built from sources for intel compilers
    - name: install hdf5 for intel build
      if: ${{ matrix.compiler == 'ifort' }}
      shell: bash
      env:
        CC: icc
        FC: ifort
        CXX: icpc
        CFLAGS: ""
      run: |
        wget -N https://support.hdfgroup.org/ftp/HDF5/current/src/hdf5-1.10.5.tar.bz2
        tar xjvf hdf5-1.10.5.tar.bz2
        cd hdf5-1.10.5
        ./configure --prefix=$HDF5_DIR --enable-fortran --disable-shared
        make install

    - name: get zlib dev libraries
      if: ${{ matrix.compiler == 'ifort' }}
      shell: bash
      run: |
        apt-get update
        apt-get install zlib1g-dev -y

    # Cache other dependencies for mcfost to avoid downloading/installing them each time this workflow runs
    - name: cache dependencies
      id: cache-deps
      uses: actions/cache@v3
      with:
        path: ${{ env.MCFOST_INSTALL }}
        key: mcfost-deps-${{ runner.os }}-${{ matrix.compiler }}-${{ hashFiles('lib/install.sh') }}

    # Only do this (lengthy) setup if dependency cache not found
    - name: prepare mcfost environment
      if: ${{ steps.cache-deps.outputs.cache-hit != 'true' }}
      shell: bash
      working-directory: lib
      run: |
        ./install.sh
