name: checks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  MCFOST_NO_XGBOOST: yes
  SYSTEM: gfortran
  MCFOST_GIT: "1"
  SKIP_HDF5: yes

jobs:
  macos:
    runs-on: macos-latest
    env:
      HDF5_DIR: /usr/local
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/build/macos
      - uses: ./.github/actions/test

  linux:
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux_2_28_x86_64
    env:
      HDF5_DIR: /usr
    steps:
      - uses: actions/checkout@v2
      # hdf5.mod file is located at /usr/lib64/gfortran/modules/ on almalinux
      - name: install hdf5
        run: |
          dnf install -y sudo wget epel-release
          dnf install -y hdf5-static redhat-lsb-core
          cd /usr/include && ln -s /usr/lib64/gfortran/modules/* .
      - run: git config --global --add safe.directory $PWD
      - uses: ./.github/actions/build/linux
      - uses: ./.github/actions/test
