name: build-test

on:
  push:
    # branches: [ master ] TODO: uncomment this
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/build/macos
      - uses: ./.github/actions/test

  linux:
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux_2_28_x86_64
    steps:
      - uses: actions/checkout@v2
      - run: dnf install -y sudo wget epel-release
      - run: dnf update -y
      - run: dnf install -y hdf5-static
      - uses: ./.github/actions/build/linux
      - uses: ./.github/actions/test
