# This is a basic workflow to help you get started with Actions

name: test-gfortran-macos

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  MCFOST_INSTALL: "/usr/local"
  MCFOST_NO_XGBOOST: "yes"
  SYSTEM: "gfortran"
  MCFOST_GIT: "1"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "test"
  test:
    # The type of runner that the job will run on
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: install gfortran
      run: brew reinstall gcc

    - name: install hdf5
      run: brew install hdf5

    - name: install cfitsio
      run: brew install cfitsio

    - name: get custom taps needed for mcfost
      run: brew tap danieljprice/all

    - name: install voro++
      run: brew install voro-dev

    - name: install sprng2
      run: brew install sprng2

    - name: compile mcfost
      run: |
        cd src
        make all INCLUDE=-I/usr/local/include LIBS=/usr/local/lib
        cd ..

    - name: run mcfost set up (downloads additional files)
      run: |
        export MCFOST_UTILS=$PWD/utils
        cd src
        ./mcfost -setup
        cd ..

    - name: download files for test suite
      run: |
        cd test_suite
        curl http://ipag.osug.fr/public/pintec/mcfost/test_data/discF_00500 -o ./test_data/discF_00500/discF_00500
        cd ..

    - name: generate reference data (currently using current commit!)
      run: |
        export MCFOST_UTILS=$PWD/utils
        cd test_suite
        ./compute_test_suite.sh

    - name: install pytest
      run: |
        python3 -m pip install pytest

    - name: test current commit against reference data
      run: |
        export MCFOST_UTILS=$PWD/utils
        cd test_suite
        python3 -m pytest -v
